services:
  - type: web
    name: salman-chat-api
    runtime: python
    rootDir: 03-hello-world
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false